### ISSUE TITLE
Error when re-arranging widgets over plot. Kinetic, 16.04

### ISSUE THREAD

**Issue by vmatos** [ros-visualization/rqt_plot#35]
When I try to re-arrange widgets in rqt, whenever I pass with it over a plot widget, I get the error:

```
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/dock_widget.py", line 90, in _event
    new_parent = self._get_new_parent(widget)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/dock_widget.py", line 139, in _get_new_parent
    widget = widget.parent()
TypeError: 'Canvas' object is not callable
```

**Comment by d4n1elchen** [comment]
So is there any workthrough for this issue for now?

**Comment by MasterEric** [comment]
I believe the consensus was that we won't get an upstream fix for this and
we will have to wait until Ros switches to Python 3 (I hate that Python 2
is still widely used, it's been a decade already!).

**Comment by bergercookie** [comment]
Hi there,

I came across this error myself and I did a bit of digging.
It's not an issue with `rqt_plot` as such, but rather with the version of matplotlib installed.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5agg.py", line 77, in paintEvent
    self.resizeEvent(event)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_plot/data_plot/mat_data_plot.py", line 110, in resizeEvent
    self.figure.tight_layout()
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 2031, in tight_layout
    self.subplots_adjust(**kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 1881, in subplots_adjust
    self.subplotpars.update(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 241, in update
    raise ValueError('bottom cannot be >= top')
ValueError: bottom cannot be >= top
[rqt-2] process has died [pid 14148, exit code -6, cmd /opt/ros/melodic/lib/rqt_gui/rqt_gui --perspective-file=/opt/ros/melodic/share/viz/rqt/a.perspective __name:=rqt __log:=/home/berger/.ros/log/faf34a34-74f0-11ea-89cc-0242ac190002/rqt-2.log].
log file: /home/berger/.ros/log/faf34a34-74f0-11ea-89cc-0242ac190002/rqt-2*.log
```

More specifically, i've encountered this issue with a particular rqt perspective configuration and matplotlib version `2.1.1`. However after upgrading to matplotlib `2.2.5` I can confirm that the error goes away and instead I get a rather harmless warning:

```
/usr/local/lib/python2.7/dist-packages/matplotlib/tight_layout.py:182: UserWarning: The bottom and top margins cannot be made large enough to accommodate all axes decorations.
  warnings.warn('The bottom and top margins cannot be made large '
```

A quickfix to this issue would be something like the following on the `rqt_plot` side:

https://github.com/ros-visualization/rqt_plot/blob/master/src/rqt_plot/data_plot/mat_data_plot.py#L110

```python
try:
    self.figure.tight_layout()
except ValueError:
    pass
```

**Comment by dirk-thomas** [comment]
> A quickfix to this issue would be something like the following on the `rqt_plot` side:

@bergercookie Please consider to create a pull request for the proposed workaround.

**Comment by roboticsengineer93** [comment]
> 2.2.5

@bergercookie Yes, it was because of matplotlib version issues, I resolved by upgrading to 2.2.5. Thanks

**Comment by lucbettaieb** [comment]
To bump this further, I encountered this issue and fixed by upgrading `matplotlib`.
```bash
sudo pip install --upgrade matplotlib
```
